USE [master]
GO

/****** Object:  Database [Switch]    Script Date: 13/08/2024 12:07:39 ******/
CREATE DATABASE [Switch]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Switch', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\Switch.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Switch_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\Switch_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Switch].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Switch] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Switch] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Switch] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Switch] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Switch] SET ARITHABORT OFF 
GO

ALTER DATABASE [Switch] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Switch] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Switch] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Switch] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Switch] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Switch] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Switch] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Switch] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Switch] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Switch] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Switch] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Switch] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Switch] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Switch] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Switch] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Switch] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Switch] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Switch] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Switch] SET  MULTI_USER 
GO

ALTER DATABASE [Switch] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Switch] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Switch] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Switch] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Switch] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Switch] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Switch] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Switch] SET  READ_WRITE 
GO

